# Generated by Django 4.0.3 on 2022-03-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
